# Must override REGISTRY and TARGET_REGISTRY Env varibles

version: 1

defaults:
  parallel: 4
  interval: 0s  # Run once
  backup: ""    # No backup

sync:
  
  - source: docker.io/apachepinot/pinot
    target: ${REGSYNC_TARGET_REGISTRY}/apachepinot/pinot
    type: repository
    tags:
      semverRange:
        - ">0.1.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/curlimages/curl
    target: ${REGSYNC_TARGET_REGISTRY}/curlimages/curl
    type: repository
    tags:
      semverRange:
        - ">8.5.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/bitnamilegacy/cassandra
    target: ${REGSYNC_TARGET_REGISTRY}/bitnamilegacy/cassandra
    type: repository
    tags:
      semverRange:
        - ">5.0.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-debian-[0-9]+-r[0-9]+'

  - source: docker.io/bitnamilegacy/kafka
    target: ${REGSYNC_TARGET_REGISTRY}/bitnamilegacy/kafka
    type: repository
    tags:
      semverRange:
        - ">4.0.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-debian-[0-9]+-r[0-9]+'

  - source: docker.io/bitnamilegacy/zookeeper
    target: ${REGSYNC_TARGET_REGISTRY}/bitnamilegacy/zookeeper
    type: repository
    tags:
      semverRange:
        - ">3.9.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-debian-[0-9]+-r[0-9]+'

  - source: docker.io/grafana/grafana
    target: ${REGSYNC_TARGET_REGISTRY}/grafana/grafana
    type: repository
    tags:
      semverRange:
        - ">12.2.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/grafana/loki
    target: ${REGSYNC_TARGET_REGISTRY}/grafana/loki
    type: repository
    tags:
      semverRange:
        - ">3.5.7"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/grafana/promtail
    target: ${REGSYNC_TARGET_REGISTRY}/grafana/promtail
    type: repository
    tags:
      semverRange:
        - ">3.5.1"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/kiwigrid/k8s-sidecar
    target: ${REGSYNC_TARGET_REGISTRY}/kiwigrid/k8s-sidecar
    type: repository
    tags:
      semverRange:
        - ">1.30.10"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/library/busybox
    target: ${REGSYNC_TARGET_REGISTRY}/library/busybox
    type: repository
    tags:
      semverRange:
        - ">1.36.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/library/memcached
    target: ${REGSYNC_TARGET_REGISTRY}/library/memcached
    type: repository
    tags:
      semverRange:
        - ">1.6.39"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-alpine'

  - source: docker.io/library/mongo-express
    target: ${REGSYNC_TARGET_REGISTRY}/library/mongo-express
    type: repository
    tags:
      semverRange:
        - ">0.1.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/library/mongo
    target: ${REGSYNC_TARGET_REGISTRY}/library/mongo
    type: repository
    tags:
      semverRange:
        - ">7.0.18"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/library/mysql
    target: ${REGSYNC_TARGET_REGISTRY}/library/mysql
    type: repository
    tags:
      semverRange:
        - ">8.0.35"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/library/nats
    target: ${REGSYNC_TARGET_REGISTRY}/library/nats
    type: repository
    tags:
      semverRange:
        - ">2.10.0"
      allow:
        - '[0-9]+\.[0-9]+-alpine'
        - '[0-9]+\.[0-9]+\.[0-9]+-alpine'

  - source: docker.io/library/postgres
    target: ${REGSYNC_TARGET_REGISTRY}/library/postgres
    type: repository
    tags:
      semverRange:
        - ">13.0.0"
      allow:
        - '[0-9]+-alpine'
        - '[0-9]+\.[0-9]+-alpine'

  - source: docker.io/library/redis
    target: ${REGSYNC_TARGET_REGISTRY}/library/redis
    type: repository
    tags:
      semverRange:
        - ">6.0.0"
      allow:
        - '[0-9]+\.[0-9]+-alpine'
        - '[0-9]+\.[0-9]+\.[0-9]+-alpine'

  - source: docker.io/oliver006/redis_exporter
    target: ${REGSYNC_TARGET_REGISTRY}/oliver006/redis_exporter
    type: repository
    tags:
      semverRange:
        - ">1.80.1"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/percona/mongodb_exporter
    target: ${REGSYNC_TARGET_REGISTRY}/percona/mongodb_exporter
    type: repository
    tags:
      semverRange:
        - ">0.47.1"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/prom/memcached-exporter
    target: ${REGSYNC_TARGET_REGISTRY}/prom/memcached-exporter
    type: repository
    tags:
      semverRange:
        - ">0.15.3"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: public.ecr.aws/docker/library/redis
    target: ${REGSYNC_TARGET_REGISTRY}/library/redis
    type: repository
    tags:
      semverRange:
        - ">7.2.8"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-alpine'

  - source: ghcr.io/dexidp/dex
    target: ${REGSYNC_TARGET_REGISTRY}/dexidp/dex
    type: repository
    tags:
      semverRange:
        - ">2.43.1"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: ghcr.io/external-secrets/external-secrets
    target: ${REGSYNC_TARGET_REGISTRY}/external-secrets/external-secrets
    type: repository
    tags:
      semverRange:
        - ">1.1.0"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: ghcr.io/kafbat/kafka-ui
    target: ${REGSYNC_TARGET_REGISTRY}/kafbat/kafka-ui
    type: repository
    tags:
      semverRange:
        - ">1.4.2"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: ghcr.io/telepresenceio/tel2
    target: ${REGSYNC_TARGET_REGISTRY}/telepresenceio/tel2
    type: repository
    tags:
      semverRange:
        - ">2.25.1"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+'

  - source: registry.k8s.io/metadata-proxy/metadata-proxy
    target: ${REGSYNC_TARGET_REGISTRY}/metadata-proxy
    type: repository
    tags:
      semverRange:
        - ">0.1.12"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: oci.external-secrets.io/external-secrets/external-secrets
    target: ${REGSYNC_TARGET_REGISTRY}/oci-external-secrets/external-secrets
    type: repository
    tags:
      semverRange:
        - ">0.20.4"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/argoproj/argocd
    target: ${REGSYNC_TARGET_REGISTRY}/argoproj/argocd
    type: repository
    tags:
      semverRange:
        - ">3.0.12"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/debezium/connect
    target: ${REGSYNC_TARGET_REGISTRY}/debezium/connect
    type: repository
    tags:
      semverRange:
        - ">3.1.1"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+\.Final'

  - source: quay.io/prometheus-operator/prometheus-config-reloader
    target: ${REGSYNC_TARGET_REGISTRY}/prometheus-operator/prometheus-config-reloader
    type: repository
    tags:
      semverRange:
        - ">0.86.2"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/prometheus-operator/prometheus-operator
    target: ${REGSYNC_TARGET_REGISTRY}/prometheus-operator/prometheus-operator
    type: repository
    tags:
      semverRange:
        - ">0.86.2"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/prometheus/node-exporter
    target: ${REGSYNC_TARGET_REGISTRY}/prometheus/node-exporter
    type: repository
    tags:
      semverRange:
        - ">1.10.2"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: quay.io/prometheus/prometheus
    target: ${REGSYNC_TARGET_REGISTRY}/prometheus/prometheus
    type: repository
    tags:
      semverRange:
        - ">3.7.3"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: docker.io/bitnamilegacy/redis-exporter
    target: ${REGSYNC_TARGET_REGISTRY}/bitnamilegacy/redis-exporter
    type: repository
    tags:
      semverRange:
        - ">1.76.0"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-debian-[0-9]+-r[0-9]+'

  - source: docker.io/bitnamilegacy/redis
    target: ${REGSYNC_TARGET_REGISTRY}/bitnamilegacy/redis
    type: repository
    tags:
      semverRange:
        - ">8.2.1"
      allow:
        - '[0-9]+\.[0-9]+\.[0-9]+-debian-[0-9]+-r[0-9]+'

  - source: registry.k8s.io/external-dns/external-dns
    target: ${REGSYNC_TARGET_REGISTRY}/external-dns/external-dns
    type: repository
    tags:
      semverRange:
        - ">0.19.0"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'

  - source: registry.k8s.io/kube-state-metrics/kube-state-metrics
    target: ${REGSYNC_TARGET_REGISTRY}/kube-state-metrics/kube-state-metrics
    type: repository
    tags:
      semverRange:
        - ">2.17.0"
      allow:
        - 'v[0-9]+\.[0-9]+\.[0-9]+'
